_core:
  default_config_hash: RSNbRD3ekSaZoE19f3eHhm93gKOcD2PtmaAVmV3XMes
langcode: es
transport: smtp
smtp_host: mailhog
smtp_port: 1025
smtp_encryption: '0'
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
smtp_credential_provider: swiftmailer
smtp_credentials:
  swiftmailer:
    username: ''
    password: ''
spool_directory: ''
